version: '3.7'

services:
  app:
    build: .
    volumes:
     - .:/app
    working_dir: /app
    ports:
     - 8080:8080
    command: ['npm', 'run' ,'serve']
    environment:
      VUE_APP_SECRET_RECAPTCHA: ${VUE_APP_SECRET_RECAPTCHA}
      VUE_APP_URL_RECAPTCHA: ${VUE_APP_URL_RECAPTCHA}
      VUE_APP_API_URL: ${VUE_APP_API_URL}