version: '3.7'

services:
  app:
    build: .
    volumes:
     - .:/app
    working_dir: /app
    ports:
     - 8080:8080
    command: ['npm', 'run' ,'serve']
    environment:
      SECRET_RECAPTCHA: 6LcXn9cUAAAAAAt20FK3qLQ0tmqZnQ2yLeUhxRkQ